version: '2'

services:
  frontend:
      build: ./angular-client
      # This line maps the contents of the client folder into the container.
      volumes:
        - ./angular-client:/usr/src/app
 
  # Build the container using the nginx Dockerfile
  nginx:
    build: ./nginx   
    # Map Nginx port 80 to the local machine's port 80
    ports:
      - "80:80"
    # Link the client container so that Nginx will have access to it
    links:
      - frontend
  
  backend:
    build: express-server
    ports:
      - '3000:3000'
    links:
        - database
    volumes:
      - ./express-server:/usr/src/app
  
  database:
    image: mongo
    ports:
      - '27017:27017'
    volumes:
      - db-data:/data/db

volumes:
  db-data: